default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root123

development:
  <<: *default
  database: invoice_store_development

test:
  <<: *default
  database: invoice_store_test

production:
  <<: *default
  database: invoice_store_production
  username: invoice_store
  password: <%= ENV['INVOICE_STORE_DATABASE_PASSWORD'] %>
